pr_repo:
- '*'

pr_readme:
- 'README.md'

pr_workflow_config:
- '.github/**/*'

pr_samples:
- 'samples/**/*'

pr_benchmark:
- 'test/benchmark/**/*'

pr_workflow_action:
- 'test/workflow/**/*'

pr_ut:
- 'test/ut/**/*'

pr_source:
- 'src/**/*'

pr_nuget:
- 'nofolder1'

dependencies:
- 'nofolder2'
