ignore_projects:
- test/ut/DebugTest/DebugTest.csproj
- test/ut/FrameworkFunctionUT/FrameworkFunctionUT.csproj
issues_template_configs:
- panel_name: " \U0001F41E 上报 BUG (Report bug)"
  file_name: bug
  panel_description: 烦请您帮助我们进步(Create a report to help us improve).
  pull_request_prefix: '[Bug]: '
  pull_request_labels:
  - name: bug
    description: Something isn't working.
    color: d73a4a
- panel_name: " \U0001F4A1 新的想法 (Feature request)"
  file_name: feature
  panel_description: 我知道您有一个比较赞的想法想和我说 (Suggest an idea for this project).
  pull_request_prefix: '[Feature]: '
  pull_request_labels:
  - name: enhancement
    description: New feature or request.
    color: a2eeef
- panel_name: " \U0001F4E3 和作者进行灵魂沟通 (Feedback)"
  file_name: feedback
  panel_description: 来聊聊咱这个库好在哪里,差在哪里和你的期待在哪里 (Give us general feedback about the repository).
  pull_request_prefix: '[Feedback]: '
  pull_request_labels:
  - name: feedback
    description: Something want to say.
    color: d4c5f9
- panel_name: " \U0001F4C3 规划任务计划 (Tasks)"
  file_name: tasks
  panel_description: 创建您的任务计划。在 ISSUE 区进行建议搜集和讨论。 (Create your task plan. Conduct suggestion collection and discussion).
  pull_request_prefix: '[Tasks]: '
  pull_request_labels:
  - name: tasks
    description: This is a tasklist.
    color: 5319e7
action:
  folded_projects: 
  global_labels:
  - name: pr_action
    description: 此次提交包含 [Action] 相关的改动.
    color: 68E0F8
  projects:
  - id: 1
    is_ignored: false
    is_folded: false
    relative_path: ''
    project_name: Action
    package_name: ''
    project_folder: .github
    labels: 
    dependency_config:
      type: github-actions
      interval: monthly
      commit_prefix: '[DEPENDENCY ACTION]'
      special_time: 05:00
      special_time_zone: Asia/Harbin
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore: 
  - id: 2
    is_ignored: false
    is_folded: false
    relative_path: ''
    project_name: Action Workflow
    package_name: ''
    project_folder: .github/workflows
    labels: 
    dependency_config:
      type: github-actions
      interval: monthly
      commit_prefix: '[DEPENDENCY ACTION]'
      special_time: 05:00
      special_time_zone: Asia/Harbin
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore: 
samples:
  folded_projects:
  - samples/PluginSample/PluginSample/PluginSample.csproj
  - samples/PluginSample/PluginA/PluginA.csproj
  - samples/PluginSample/PluginB/PluginB.csproj
  - samples/PluginSample/PluginBase/PluginBase.csproj
  - samples/ReferenceSample/ReferenceSample.csproj
  - samples/HotReloadSample/HotReloadSample.csproj
  - samples/HotReloadPlugin/HotReloadPlugin.csproj
  global_labels:
  - name: pr_samples
    description: 此次提交包含 [案例工程] 相关的改动.
    color: 68E0F8
  projects: []
src:
  folded_projects:
  - src/Natasha.CSharp/Extension/Natasha.CSharp.Extension.Ambiguity/Natasha.CSharp.Extension.Ambiguity.csproj
  - src/Natasha.CSharp/Extension/Natasha.CSharp.Extension.Codecov/Natasha.CSharp.Extension.Codecov.csproj
  global_labels:
  - name: pr_src
    description: 此次提交包含 [源码工程] 相关的改动.
    color: 68E0F8
  projects:
  - using_output:
      enable: true
      ignores:
      - System
      - System.Runtime.CompilerServices
      - System.Reflection
    id: 6A64FCC4-0E19-4181-ABD8-D951DB6B75E9
    is_ignored: false
    is_folded: false
    relative_path: src/Natasha.CSharp/Natasha.CSharp.Compiler/Natasha.CSharp.Compiler.csproj
    project_name: Natasha.CSharp.Compiler
    package_name: DotNetCore.Natasha.CSharp.Compiler
    project_folder: src/Natasha.CSharp/Natasha.CSharp.Compiler
    labels: 
    dependency_config:
      type: nuget
      interval: daily
      commit_prefix: '[DEPENDENCY SRC]'
      special_time: 
      special_time_zone: 
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore:
      - name: Microsoft.Extensions.DependencyModel
        versions: 
        versions_type: 
  - using_output:
      enable: true
      ignores:
      - System
      - System.Runtime.CompilerServices
      - System.Reflection
    id: A6A252E0-BC83-43D1-A118-371721F1A5D4
    is_ignored: false
    is_folded: false
    relative_path: src/Natasha.CSharp/Natasha.DynamicLoad.Base/Natasha.DynamicLoad.Base.csproj
    project_name: Natasha.DynamicLoad.Base
    package_name: DotNetCore.Natasha.DynamicLoad.Base
    project_folder: src/Natasha.CSharp/Natasha.DynamicLoad.Base
    labels: 
    dependency_config: 
  - using_output:
      enable: true
      ignores:
      - System
      - System.Runtime.CompilerServices
      - System.Reflection
    id: 02D796A3-A9FB-4E9C-972C-50B173DE213C
    is_ignored: false
    is_folded: false
    relative_path: src/Natasha.CSharp/Component/Core/Natasha.Domain/Natasha.Domain.csproj
    project_name: Natasha.Domain
    package_name: DotNetCore.Natasha.Domain
    project_folder: src/Natasha.CSharp/Component/Core/Natasha.Domain
    labels: 
    dependency_config: 
  - using_output:
      enable: true
      ignores:
      - System
      - System.Runtime.CompilerServices
      - System.Reflection
    id: CE5B5331-3F4F-412F-8169-8DA1D37170C6
    is_ignored: false
    is_folded: false
    relative_path: src/Natasha.CSharp/Component/Core/Natasha.CSharp.Compiler.Domain/Natasha.CSharp.Compiler.Domain.csproj
    project_name: Natasha.CSharp.Compiler.Domain
    package_name: 
    project_folder: src/Natasha.CSharp/Component/Core/Natasha.CSharp.Compiler.Domain
    labels: 
    dependency_config: 
  - using_output:
      enable: true
      ignores:
      - System
      - System.Runtime.CompilerServices
      - System.Reflection
    id: 1A79A124-5C6D-456E-8402-33A1FA68C566
    is_ignored: false
    is_folded: false
    relative_path: src/Natasha.CSharp/Component/Core/Natasha.CSharp.Template.Core/Natasha.CSharp.Template.Core.csproj
    project_name: Natasha.CSharp.Template.Core
    package_name: DotNetCore.Natasha.CSharp.Template.Core
    project_folder: src/Natasha.CSharp/Component/Core/Natasha.CSharp.Template.Core
    labels: 
    dependency_config: 
test:
  folded_projects: []
  global_labels:
  - name: pr_test
    description: 此次提交包含 [测试工程] 相关的改动.
    color: 68E0F8
  projects:
  - trigger_pull_request_test: true
    trigger_codecov: true
    id: 7EC1DFB6-3332-4A4D-867B-B7C32D2AB0FE
    is_ignored: false
    is_folded: false
    relative_path: test/ut/NatashaFunctionUT/NatashaFunctionUT.csproj
    project_name: NatashaFunctionUT
    package_name: NatashaFunctionUT
    project_folder: test/ut/NatashaFunctionUT
    labels: 
    dependency_config: 
  - trigger_pull_request_test: false
    trigger_codecov: false
    id: 716B9CEC-8CA2-433F-9E9A-974E536C4099
    is_ignored: false
    is_folded: false
    relative_path: test/ut/PluginFunctionUT/PluginFunctionUT.csproj
    project_name: PluginFunctionUT
    package_name: 
    project_folder: test/ut/PluginFunctionUT
    labels: 
    dependency_config: 
workflow:
  folded_projects:
  - test/workflow/Workflow.Initialization/Workflow.Initialization.csproj
  - test/workflow/Workflow.Nuget.Publish/Workflow.Nuget.Publish.csproj
  - test/workflow/Workflow.Runner/Workflow.Runner.csproj
  - test/workflow/Github.NET.Sdk/Github.NET.Sdk.csproj
  - test/workflow/Solution.NET.Sdk/Solution.NET.Sdk.csproj
  - test/workflow/Github.NMSAcion.NET.Sdk/Github.NMSAcion.NET.Sdk.csproj
  global_labels:
  - name: pr_workflow
    description: 此次提交包含 [管道功能] 相关的改动.
    color: 68E0F8
  projects:
  - id: 199906B2-7FED-4DFF-8364-C5C66A787F02
    is_ignored: false
    is_folded: false
    relative_path: test/workflow/Github.NMSAction.NET.Sdk/Github.NMSAction.NET.Sdk.csproj
    project_name: Github.NMSAction.NET.Sdk
    package_name: 
    project_folder: test/workflow/Github.NMSAction.NET.Sdk
    labels: 
    dependency_config: 
