ignore_projects:
- test/ut/PluginLibraries/DN_DV/DNDV1
- test/ut/PluginLibraries/DN_DV/DNDV2
- test/ut/PluginLibraries/DN_SV/DNSV1
- test/ut/PluginLibraries/DN_SV/DNSV2
- test/ut/PluginLibraries/MetadataDiff/MetadataDiff
- test/ut/PluginLibraries/SNDV_DV/SNDVDV
- test/ut/PluginLibraries/SNDV_SV/SNDVSV
- test/ut/PluginLibraries/SNIV_DV/SNIVDV
- test/ut/PluginLibraries/SNIV_SV/SNIVSV
- test/ut/DebugTest
- test/ut/NatashaUT
- test/ut/PluginLibraries/Plugin1
- test/ut/PluginLibraries/Plugin2
- test/ut/PluginLibraries/PluginBase
issues_template_configs:
- template_name: " \U0001F41E 上报 BUG (Report bug)"
  template_file_name: bug
  template_description: 烦请您帮助我们进步(Create a report to help us improve).
  title_prefix: '[Bug]: '
  labels:
  - name: bug
    description: Something isn't working.
    color: d73a4a
- template_name: " \U0001F4A1 新的想法 (Feature request)"
  template_file_name: feature
  template_description: 我知道您有一个比较赞的想法想和我说 (Suggest an idea for this project).
  title_prefix: '[Feature]:'
  labels:
  - name: enhancement
    description: New feature or request.
    color: a2eeef
- template_name: " \U0001F4E3 和作者进行灵魂沟通 (Feedback)"
  template_file_name: feedback
  template_description: 来聊聊咱这个库好在哪里,差在哪里和你的期待在哪里 (Give us general feedback about the repository).
  title_prefix: '[Feedback]:'
  labels:
  - name: feedback
    description: Something want to say.
    color: d4c5f9
action:
  folded_projects: 
  global_labels:
  - name: pr_action
    description: 此次提交包含 [Action] 相关的改动.
    color: 68E0F8
  projects:
  - is_ignored: false
    is_folded: false
    project_name: Action
    project_folder: .github
    labels: 
    dependency_config:
      type: github-actions
      interval: monthly
      commit_prefix: '[DEPENDENCY ACTION]'
      special_time: 05:00
      special_time_zone: Asia/Harbin
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore: 
  - is_ignored: false
    is_folded: false
    project_name: Action Workflow
    project_folder: .github/workflows
    labels: 
    dependency_config:
      type: github-actions
      interval: monthly
      commit_prefix: '[DEPENDENCY ACTION]'
      special_time: 05:00
      special_time_zone: Asia/Harbin
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore: 
samples:
  folded_projects:
  - samples/ReferenceSample
  - samples/PluginSample/PluginA
  - samples/PluginSample/PluginB
  - samples/PluginSample/PluginBase
  - samples/PluginSample/PluginSample
  global_labels:
  - name: pr_samples
    description: 此次提交包含 [案例工程] 相关的改动.
    color: 68E0F8
  projects: []
src:
  folded_projects: []
  global_labels:
  - name: pr_src
    description: 此次提交包含 [源码工程] 相关的改动.
    color: 68E0F8
  projects:
  - using_output:
      enable: true
      ignores: 
    is_ignored: false
    is_folded: false
    unique_file_path:
    project_name: Natasha.Domain
    project_folder: src/Natasha.Domain
    labels: 
    dependency_config:
      type: nuget
      interval: daily
      commit_prefix: '[DEPENDENCY SRC]'
      special_time: 
      special_time_zone: 
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore:
      - name: System.Reflection.MetadataLoadContext
        versions: 
        versions_type: 
      - name: Microsoft.Extensions.DependencyModel
        versions: 
        versions_type: 
  - using_output:
      enable: true
      ignores: 
    is_ignored: false
    is_folded: false
    project_name: Natasha.CSharp
    project_folder: src/Natasha.CSharp/Natasha.CSharp
    labels: 
    dependency_config:
      type: nuget
      interval: daily
      commit_prefix: '[DEPENDENCY SRC]'
      special_time: 
      special_time_zone: 
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore:
      - name: System.Reflection.MetadataLoadContext
        versions: 
        versions_type: 
      - name: Microsoft.Extensions.DependencyModel
        versions: 
        versions_type: 
  - using_output:
      enable: true
      ignores: 
    is_ignored: false
    is_folded: false
    project_name: Natasha.CSharp.Extension.Ambiguity
    project_folder: src/Natasha.CSharp/Extension/Natasha.CSharp.Extension.Ambiguity
    labels: 
    dependency_config:
      type: nuget
      interval: daily
      commit_prefix: '[DEPENDENCY SRC]'
      special_time: 
      special_time_zone: 
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore:
      - name: System.Reflection.MetadataLoadContext
        versions: 
        versions_type: 
      - name: Microsoft.Extensions.DependencyModel
        versions: 
        versions_type: 
test:
  folded_projects: []
  global_labels:
  - name: pr_test
    description: 此次提交包含 [测试工程] 相关的改动.
    color: 68E0F8
  projects:
  - trigger_pull_request_test: false
    trigger_codecov: false
    is_ignored: false
    is_folded: false
    project_name: FrameworkFunctionUT
    project_folder: test/ut/FrameworkFunctionUT
    labels: 
    dependency_config: 
  - trigger_pull_request_test: true
    trigger_codecov: true
    is_ignored: false
    is_folded: false
    project_name: NatashaFunctionUT
    project_folder: test/ut/NatashaFunctionUT
    labels: 
    dependency_config:
      type: nuget
      interval: weekly
      commit_prefix: '[DEPENDENCY TEST]'
      special_time: 
      special_time_zone: 
      labels:
      - name: dependencies
        description: 有依赖需要升级
        color: 4E04B0
      ignore: 
workflow:
  folded_projects:
  - test/workflow/Github.NET.Sdk
  - test/workflow/Workflow.Initialization
  - test/workflow/Workflow.Nuget.Publish
  - test/workflow/Workflow.Runner
  global_labels:
  - name: pr_workflow
    description: 此次提交包含 [管道功能] 相关的改动.
    color: 68E0F8
  projects: []
