name: 📃 规划任务计划 (Tasks)
description: 创建您的任务计划。在 ISSUE 区进行意见搜集和讨论 (Create your task plan. Conduct suggestion collection and discussion).
title: "[Tasks]: 有关【xxx】相关功能的规划与任务细化 (意见搜集与讨论)"
labels: ["tasks"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您为此项目提出具体的任务计划.(Thank you for proposing specific task plans for this project!)

  - type: textarea
    id: repro
    attributes:
      label: 📃 计划清单 (Tasklist).
      description: 请简单清晰地描述一下每条任务, 每行之间不要出现换行。(Please describe each task simply and clearly.).
      value: |

        ```[tasklist]
        ### 删除并添加标题
        - [x] 1.  已完成计划xxxx。
        - [ ] 2.  未完成计划xxxxx。
        ```

    validations:
      required: true


