name: .NET

on:
   pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:

    linux:
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      runs-on: ubuntu-latest
      
      steps:
      - uses: actions/checkout@v2
      - name: 🔨 Setup .NET Core 3.1.X SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
        
      - name: 🔨 Setup .NET 5.0.X SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: 🔨 Setup .NET 6.X SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          
      - name: 🚦 Test
        run: dotnet test './test/NatashaFunctionUT' -c Release
     
    windows:
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      runs-on: windows-latest  
      steps:
      - uses: actions/checkout@v2
      - name: 🔨 Setup .NET Core 3.1.X SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
        
      - name: 🔨 Setup .NET 5.0.X SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: 🔨 Setup .NET 6.X SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
    
      - name: Setup Cover
        uses: crazy-max/ghaction-chocolatey@v1
        with: 
          args: install codecov
          
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build "./test/NatashaFunctionUT"
      - name: 🚦 Test
        run: dotnet test "./test/NatashaFunctionUT/NatashaFunctionUT.csproj" --no-restore -f net5.0 -c Release --collect:"XPlat Code Coverage" -r ./coverage

      - name: Upload to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.COVERAGE_KEY }}
          directory: ./coverage/
   
    mac:
      if: github.event_name == 'pull_request' && github.event.action != 'closed'
      runs-on: macos-latest
            
      steps:
      - uses: actions/checkout@v2
      - name: 🔨 Setup .NET Core 3.1.X SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
        
      - name: 🔨 Setup .NET 5.0.X SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.x'

      - name: 🔨 Setup .NET 6.X SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          
      - name: 🚦 Test
        run: dotnet test './test/NatashaFunctionUT' -c Release
