name: .NET

on:
   push:
    branches:
    - master

jobs:
  linux:      
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET SDK 3.1.22
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.22'
      - name: Setup .NET SDK 5.0.13
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '5.0.13'
      - name: Setup .NET SDK 6.0.1
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '6.0.1'
      - name: Build
        run: dotnet build './src/Natasha.CSharp/Natasha.CSharp/Natasha.CSharp.csproj' --configuration Release
      - name: Test
        run: dotnet test './test/NatashaFunctionUT' --no-restore --no-build
     
  windows:
      runs-on: windows-latest
      strategy:
         matrix:
            dotnet: ['6.0.1']
            
      steps:
       - name : CheckOut Code
         uses: actions/checkout@v2
       - name: Setup .NET ${{ matrix.dotnet-version }}
         uses: actions/setup-dotnet@v1.7.2
         with:
          dotnet-version: ${{ matrix.dotnet-version }}
    
       - name: Setup Cover
         uses: crazy-max/ghaction-chocolatey@v1
         with: 
            args: install codecov
     
       - name: Build
         run: dotnet build './src/Natasha.CSharp/Natasha.CSharp/Natasha.CSharp.csproj' --configuration Release
         
       - name: Test
         run: dotnet test  "./test/NatashaFunctionUT/NatashaFunctionUT.csproj"  /p:CollectCoverage=true /p:CoverletOutputFormat=json  --collect:"XPlat Code Coverage" -r:"./result/" --no-build -m
       
       - name: Upload Report
         run: codecov -f "*.cobertura.xml" -t ${{ secrets.COVERAGE_KEY }}
   
  mac:
      runs-on: macos-latest
      strategy:
         matrix:
            dotnet: ['3.1.22', '5.0.13','6.0.1' ]
            
      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Build
        run: dotnet build './src/Natasha.CSharp/Natasha.CSharp/Natasha.CSharp.csproj' -f ${{ matrix.dotnet-version }} --configuration Release
      - name: Test
        run: dotnet test './test/NatashaFunctionUT' --runtime ${{ matrix.dotnet-version }}
