name: .NET Core

on:
   push:
    branches:
    - master

jobs:
  linux:      
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Build
        run: dotnet build './src/Natasha.CSharp/Natasha.CSharp.All/Natasha.CSharp.All.csproj' --configuration Release
      - name: Test
        run: dotnet test './test/NatashaUT'
     
  windows:
      runs-on: windows-latest
      steps:
       - name : CheckOut Code
         uses: actions/checkout@v1
       - name: Setup
         uses: actions/setup-dotnet@v1
         with:
          dotnet-version: 5.0.100
    
       - name: Setup Cover
         uses: crazy-max/ghaction-chocolatey@v1
         with: 
            args: install codecov
     
       - name: Build
         run: dotnet build './src/Natasha.CSharp/Natasha.CSharp.All/Natasha.CSharp.All.csproj' --configuration Release
         
       - name: Test
         run: dotnet test  "./test/NatashaUT/NatashaUT.csproj" /p:CollectCoverage=true /p:CoverletOutputFormat=json  --collect:"XPlat Code Coverage" -r:"./result/" --no-build -m
       
       - name: Upload Report
         run: codecov -f "*.cobertura.xml" -t ${{ secrets.COVERAGE_KEY }}
   
  mac:
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v1
      - name: Setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100
      - name: Build
        run: dotnet build './src/Natasha.CSharp/Natasha.CSharp.All/Natasha.CSharp.All.csproj' --configuration Release
      - name: Test
        run: dotnet test './test/NatashaUT'
